"""Exports a scoring fixture the iOS port is tested against.

`app/src/phase2/climaxScoring.ts` is a port of `scoring_algorithm.py`. Ports
drift. This writes a deterministic feature grid, a word list, and the scores
*this* implementation produces for them, so `climaxScoring.test.ts` can assert
the TypeScript agrees to 6 decimal places.

Only the scorer is exercised — no video, no whisper, no OpenCV — because the
scorer is the part that is shared logic. Feature *extraction* is native on iOS
and deliberately not bit-identical (Vision's optical flow is not OpenCV's
Lucas-Kanade); min-max normalisation across the candidates of one video is what
makes a correlated-but-different estimator acceptable there.

    python3 export_parity_fixture.py

Rerun and commit the fixture whenever the scoring maths changes.
"""
from __future__ import annotations

import json
import os

import numpy as np

from audio_vision_engine import FeatureGrid
from scoring_algorithm import HookScorer, ScoringConfig, ScoringWeights
from transcriber import Transcript, Word

OUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "..", "app", "__tests__", "fixtures", "climax-parity.json",
)

GRID_HZ = 20.0
DURATION = 40.0
SIGNALS = (
    "audio.rms", "audio.flux", "audio.zcr", "audio.peaks",
    "visual.flow", "visual.frame_diff", "visual.scene_change",
)


def build_grid() -> FeatureGrid:
    """Deterministic signals with a genuine peak, so a winner actually exists.

    Structure matters more than realism: a flat grid would make every candidate
    tie and the comparison would pass no matter how wrong the port was.
    """
    rng = np.random.default_rng(20260802)
    n = int(DURATION * GRID_HZ)
    times = np.arange(n) / GRID_HZ
    signals = {}
    for i, name in enumerate(SIGNALS):
        base = rng.random(n) * 0.3
        # A bump centred at 22s, offset per signal so the modalities disagree
        # slightly — a single shared peak would not exercise the weighting.
        centre = 22.0 + (i - 3) * 0.4
        bump = np.exp(-0.5 * ((times - centre) / 1.6) ** 2)
        drift = 0.15 * np.sin(times / 7.0 + i)
        sig = base + bump + drift
        if name == "audio.peaks":
            # An impulse train, as the real extractor produces.
            sig = (sig > 0.85).astype(np.float64)
        signals[name] = np.clip(sig, 0.0, None)
    return FeatureGrid(
        hop=1.0 / GRID_HZ, times=times, duration=DURATION, signals=signals
    )


def build_words() -> list:
    """A word list with the things the speech features actually look for:
    keywords, a consecutive repetition run, an elongated spelling, and words
    held well past the median."""
    script = [
        ("okay", 0.30), ("so", 0.22), ("we're", 0.25), ("just", 0.24),
        ("walking", 0.36), ("around", 0.30), ("here", 0.28), ("and", 0.20),
        ("nothing", 0.34), ("is", 0.18), ("really", 0.30), ("happening", 0.40),
        ("at", 0.16), ("all", 0.26), ("right", 0.28), ("now", 0.30),
        ("wait", 0.42), ("wait", 0.40), ("wait", 0.44),
        ("look", 0.52), ("at", 0.20), ("that", 0.46),
        ("nooo", 0.95), ("way", 0.88), ("that's", 0.40), ("insane", 0.92),
        ("did", 0.24), ("you", 0.20), ("see", 0.48), ("that", 0.44),
        ("holy", 0.60), ("that", 0.30), ("was", 0.26), ("crazy", 0.70),
        ("okay", 0.30), ("anyway", 0.36), ("let's", 0.28), ("keep", 0.26),
        ("going", 0.34), ("i", 0.16), ("guess", 0.32), ("that", 0.22),
        ("is", 0.18), ("about", 0.28), ("it", 0.20), ("for", 0.18),
        ("today", 0.40), ("thanks", 0.36), ("for", 0.18), ("watching", 0.44),
    ]
    words = []
    t = 1.2
    for i, (text, dur) in enumerate(script):
        # A gap before the exciting stretch, so novelty has something to see.
        if i == 16:
            t += 1.4
        words.append(Word(text=text, start=round(t, 4), end=round(t + dur, 4)))
        t += dur + (0.06 if 16 <= i <= 33 else 0.18)
    return words


def main() -> int:
    grid = build_grid()
    words = build_words()
    # No segments: Apple's Speech framework returns per-word substrings with no
    # punctuation, so the iOS port has no exclamation-mark signal at all. An
    # empty segment list zeroes that component here too, which is what makes
    # the two comparable rather than approximately comparable.
    transcript = Transcript(words=words, segments=[])

    config = ScoringConfig(
        window_sizes=(3.0, 4.0, 5.0, 6.0, 7.0),
        preferred_size=4.0,
        stride=0.5,
        weights=ScoringWeights(),
        context_seconds=5.0,
    )
    ranked = HookScorer(config).rank(grid, transcript)

    fixture = {
        "_comment": "Generated by server/climax/export_parity_fixture.py. Do not edit.",
        "gridHz": GRID_HZ,
        "duration": DURATION,
        "times": [round(float(t), 6) for t in grid.times],
        "signals": {
            name: [round(float(v), 9) for v in sig]
            for name, sig in grid.signals.items()
        },
        "words": [
            {"text": w.text, "start": w.start, "end": w.end} for w in words
        ],
        "config": {
            "windowSizes": list(config.window_sizes),
            "preferredSize": config.preferred_size,
            "stride": config.stride,
            "weights": {
                "audio": config.weights.audio, "visual": config.weights.visual,
                "speech": config.weights.speech, "novelty": config.weights.novelty,
            },
            "contextSeconds": config.context_seconds,
            "sizePreference": config.size_preference,
        },
        "ranked": [
            {
                "start": round(r.start, 6), "end": round(r.end, 6),
                "score": round(r.score, 9), "confidence": round(r.confidence, 9),
                "reason": {k: round(v, 9) for k, v in r.reason.items()},
            }
            for r in ranked[:12]
        ],
        "candidateCount": len(ranked),
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(os.path.normpath(OUT), "w", encoding="utf-8") as fh:
        json.dump(fixture, fh, indent=1)
    best = ranked[0]
    print(f"wrote {os.path.normpath(OUT)}")
    print(f"{len(ranked)} candidates; best {best.start:.2f}-{best.end:.2f}s "
          f"score={best.score:.4f} confidence={best.confidence:.4f}")
    print(json.dumps(best.to_dict()["reason"], indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
