import fixture from './fixtures/climax-parity.json';
import type { TimedWord } from '../src/captions/captionTimeline';
import type { FeatureGrid, ScoringConfig } from '../src/editing/climaxScoring';
import {
  DEFAULT_SCORING,
  medianWordDuration,
  minmax,
  normaliseWeights,
  percentile,
  rankHooks,
  resolveWeights,
  speechFeatures,
  weightsWithoutSpeech,
  windowMeans,
  wordsBetween,
} from '../src/editing/climaxScoring';

/**
 * `climaxScoring.ts` is a port of server/climax/scoring_algorithm.py. The
 * fixture is generated by export_parity_fixture.py from that implementation,
 * so these tests fail if the two ever disagree.
 */

const grid: FeatureGrid = {
  hop: 1 / fixture.gridHz,
  times: fixture.times,
  duration: fixture.duration,
  signals: fixture.signals as Record<string, number[]>,
};
const words: TimedWord[] = fixture.words;
const config: ScoringConfig = {
  windowSizes: fixture.config.windowSizes,
  preferredSize: fixture.config.preferredSize,
  stride: fixture.config.stride,
  weights: fixture.config.weights,
  contextSeconds: fixture.config.contextSeconds,
  sizePreference: fixture.config.sizePreference,
};

describe('parity with scoring_algorithm.py', () => {
  const ranked = rankHooks(grid, words, config);

  it('enumerates the same candidate windows', () => {
    expect(ranked).toHaveLength(fixture.candidateCount);
  });

  it('picks the same winner', () => {
    expect(ranked[0].start).toBeCloseTo(fixture.ranked[0].start, 6);
    expect(ranked[0].end).toBeCloseTo(fixture.ranked[0].end, 6);
  });

  it('agrees on score, confidence and every modality, window by window', () => {
    fixture.ranked.forEach((expected, i) => {
      const actual = ranked[i];
      expect(actual.start).toBeCloseTo(expected.start, 6);
      expect(actual.end).toBeCloseTo(expected.end, 6);
      expect(actual.score).toBeCloseTo(expected.score, 6);
      expect(actual.confidence).toBeCloseTo(expected.confidence, 6);
      for (const key of Object.keys(expected.reason)) {
        expect(actual.reason[key]).toBeCloseTo(
          (expected.reason as Record<string, number>)[key],
          6,
        );
      }
    });
  });

  it('ranks strictly by score, best first', () => {
    ranked.slice(1).forEach((window, i) => {
      expect(ranked[i].score).toBeGreaterThanOrEqual(window.score);
    });
  });
});

describe('normalisation', () => {
  it('maps a constant signal to zeros rather than NaN', () => {
    expect(minmax([4, 4, 4])).toEqual([0, 0, 0]);
    expect(minmax([])).toEqual([]);
  });

  it('scales to [0, 1]', () => {
    expect(minmax([2, 4, 6])).toEqual([0, 0.5, 1]);
  });

  it('matches numpy percentile interpolation', () => {
    // numpy.percentile([1,2,3,4], 50) == 2.5, not 2 or 3.
    expect(percentile([1, 2, 3, 4], 50)).toBeCloseTo(2.5, 9);
    expect(percentile([1, 2, 3, 4], 95)).toBeCloseTo(3.85, 9);
    expect(percentile([7], 50)).toBe(7);
    expect(percentile([], 50)).toBe(0);
  });
});

describe('weights', () => {
  it('normalises to sum 1', () => {
    const w = normaliseWeights({ audio: 2, visual: 2, speech: 2, novelty: 2 });
    expect(w.audio + w.visual + w.speech + w.novelty).toBeCloseTo(1, 9);
    expect(w.audio).toBeCloseTo(0.25, 9);
  });

  it('redistributes speech proportionally when there is none', () => {
    const w = weightsWithoutSpeech(DEFAULT_SCORING.weights);
    expect(w.speech).toBe(0);
    expect(w.audio + w.visual + w.novelty).toBeCloseTo(1, 9);
    // Proportions between the survivors are preserved.
    expect(w.audio / w.visual).toBeCloseTo(0.35 / 0.25, 9);
  });

  it('rejects weights that cannot carry the redistribution', () => {
    expect(() =>
      weightsWithoutSpeech({ audio: 0, visual: 0, speech: 1, novelty: 0 }),
    ).toThrow();
    expect(() =>
      normaliseWeights({ audio: 0, visual: 0, speech: 0, novelty: 0 }),
    ).toThrow();
  });

  it('resolveWeights matches weightsWithoutSpeech for the speech case', () => {
    const general = resolveWeights(DEFAULT_SCORING.weights, {
      audio: true,
      visual: true,
      speech: false,
    });
    const specific = weightsWithoutSpeech(DEFAULT_SCORING.weights);
    expect(general.audio).toBeCloseTo(specific.audio, 12);
    expect(general.visual).toBeCloseTo(specific.visual, 12);
    expect(general.novelty).toBeCloseTo(specific.novelty, 12);
    expect(general.speech).toBe(0);
  });

  it('carries a video-only clip on visual and novelty alone', () => {
    // Glasses capture is routinely video-only, so this is a normal clip.
    const w = resolveWeights(DEFAULT_SCORING.weights, {
      audio: false,
      visual: true,
      speech: false,
    });
    expect(w.audio).toBe(0);
    expect(w.speech).toBe(0);
    expect(w.visual + w.novelty).toBeCloseTo(1, 9);
  });

  it('scores silent footage without pinning a quarter of it to zero', () => {
    const silent = rankHooks(grid, [], config);
    expect(silent[0].reason.speech).toBe(0);
    // With speech redistributed, the remaining modalities must still separate
    // the winner from the pack.
    expect(silent[0].score).toBeGreaterThan(0.5);
    expect(silent[0].confidence).toBeGreaterThan(0.5);
  });
});

describe('speech features', () => {
  const w = (text: string, start: number, end: number): TimedWord => ({
    text,
    start,
    end,
  });

  it('counts words by midpoint, so a straddling word belongs to one window', () => {
    // 'a' spans 0.9-1.3, so its midpoint is 1.1 — it is counted once, by the
    // window its middle lands in, not by both windows it overlaps.
    const list = [w('a', 0.9, 1.3), w('b', 1.4, 1.6)];
    expect(wordsBetween(list, 0, 1.0).map(x => x.text)).toEqual([]);
    expect(wordsBetween(list, 1.0, 1.2).map(x => x.text)).toEqual(['a']);
    expect(wordsBetween(list, 1.2, 2).map(x => x.text)).toEqual(['b']);
  });

  it('puts a midpoint exactly on the boundary in the later window', () => {
    const list = [w('a', 0.9, 1.3)]; // midpoint exactly 1.1
    expect(wordsBetween(list, 0, 1.1)).toEqual([]);
    expect(wordsBetween(list, 1.1, 2).map(x => x.text)).toEqual(['a']);
  });

  it('rates are per second, so a longer window is not automatically hotter', () => {
    const list = [w('go', 0, 0.3), w('go', 0.3, 0.6), w('go', 0.6, 0.9)];
    const short = speechFeatures(list, 0, 1);
    const long = speechFeatures(list, 0, 2);
    expect(short['speech.speaking_rate']).toBeCloseTo(3, 6);
    expect(long['speech.speaking_rate']).toBeCloseTo(1.5, 6);
  });

  it('scores consecutive repetition, not mere recurrence', () => {
    const run = [w('go', 0, 0.3), w('go', 0.3, 0.6), w('go', 0.6, 0.9)];
    const apart = [w('go', 0, 0.3), w('and', 0.3, 0.6), w('go', 0.6, 0.9)];
    expect(speechFeatures(run, 0, 1)['speech.repetition']).toBeGreaterThan(
      speechFeatures(apart, 0, 1)['speech.repetition'],
    );
  });

  it('reads stretched delivery as emphasis', () => {
    const list = [w('no', 0, 0.2), w('waaay', 0.2, 1.4)];
    const median = medianWordDuration(list);
    expect(speechFeatures(list, 0, 2, median)['speech.emphasis']).toBeGreaterThan(0);
  });

  it('ignores sentiment — only delivery', () => {
    const terrible = [w('this', 0, 0.2), w('is', 0.2, 0.4), w('terrible', 0.4, 0.9)];
    const amazing = [w('this', 0, 0.2), w('is', 0.2, 0.4), w('wonderful', 0.4, 0.9)];
    expect(speechFeatures(terrible, 0, 1)['speech.speaking_rate']).toBeCloseTo(
      speechFeatures(amazing, 0, 1)['speech.speaking_rate'],
      9,
    );
  });

  it('returns zeros for a window with no words', () => {
    expect(speechFeatures([], 0, 3)).toEqual({
      'speech.keyword_density': 0,
      'speech.speaking_rate': 0,
      'speech.repetition': 0,
      'speech.emphasis': 0,
    });
  });
});

describe('grid access', () => {
  it('averages over a half-open window', () => {
    const tiny: FeatureGrid = {
      hop: 0.5,
      times: [0, 0.5, 1.0, 1.5],
      duration: 2,
      signals: { 'audio.rms': [0, 1, 2, 3] },
    };
    expect(windowMeans(tiny, 0, 1)['audio.rms']).toBeCloseTo(0.5, 9);
    expect(windowMeans(tiny, 0, 2)['audio.rms']).toBeCloseTo(1.5, 9);
    // Empty slice is 0, never NaN.
    expect(windowMeans(tiny, 5, 6)['audio.rms']).toBe(0);
  });

  it('scores a clip shorter than the smallest window as one whole window', () => {
    const tiny: FeatureGrid = {
      hop: 0.5,
      times: [0, 0.5, 1.0, 1.5],
      duration: 2,
      signals: {
        'audio.rms': [0, 1, 2, 3],
        'visual.flow': [3, 2, 1, 0],
      },
    };
    const ranked = rankHooks(tiny, [], DEFAULT_SCORING);
    expect(ranked).toHaveLength(1);
    expect(ranked[0].start).toBe(0);
    expect(ranked[0].end).toBeCloseTo(2, 6);
  });
});

describe('novelty', () => {
  it('is zero at the very start, where there is nothing to be novel against', () => {
    const ranked = rankHooks(grid, words, config);
    const opening = ranked.find(r => r.start === 0);
    expect(opening).toBeDefined();
    expect(opening!.reason.novelty).toBe(0);
  });
});

describe('missing signals', () => {
  it('scores the visual modality from whatever the extractor produced', () => {
    // Dense optical flow is skipped on device, so visual.flow is absent
    // rather than zero. An absent signal must not average in as a constant.
    const withFlow: FeatureGrid = {
      ...grid,
      signals: { ...grid.signals },
    };
    const withoutFlow: FeatureGrid = {
      ...grid,
      signals: Object.fromEntries(
        Object.entries(grid.signals).filter(([k]) => k !== 'visual.flow'),
      ),
    };
    const a = rankHooks(withFlow, words, config)[0];
    const b = rankHooks(withoutFlow, words, config)[0];
    // Both still produce a real visual score rather than a deflated one.
    expect(b.reason.visual).toBeGreaterThan(0);
    expect(Object.keys(b.detail)).not.toContain('visual.flow');
    expect(Object.keys(a.detail)).toContain('visual.flow');
  });

  it('scores a video-only clip with no audio signals at all', () => {
    const videoOnly: FeatureGrid = {
      ...grid,
      signals: Object.fromEntries(
        Object.entries(grid.signals).filter(([k]) => !k.startsWith('audio.')),
      ),
    };
    const ranked = rankHooks(videoOnly, [], config);
    expect(ranked[0].reason.audio).toBe(0);
    expect(ranked[0].reason.speech).toBe(0);
    expect(ranked[0].score).toBeGreaterThan(0.5);
  });
});
