#!/bin/sh
# Lifts `JVSReadVideoColor` out of ClipStitcher.m into lifted.h, verbatim.
#
# The harness has to test the function that ships, not a re-typing of it. A
# copy-paste would drift the first time the shipping one changed and the probe
# would then be confirming something the app no longer does — which is worse
# than having no probe, because it reads as evidence.
set -e
DIR=$(dirname "$0")
SRC="$DIR/../../../app/modules/clip-stitcher/ios/ClipStitcher.m"
python3 - "$SRC" "$DIR/lifted.h" <<'PY'
import io, sys
src = io.open(sys.argv[1], encoding='utf-8').read()
start = src.index('typedef struct {\n  BOOL isHDR;')
end = src.index('  return info;\n}', start) + len('  return info;\n}')
io.open(sys.argv[2], 'w', encoding='utf-8').write(
    '// GENERATED by sync.sh from ClipStitcher.m. Do not edit.\n'
    + src[start:end] + '\n')
print('lifted %d bytes' % (end - start))
PY
